import { ArrowDownRight, ArrowRight, ArrowUpRight, BriefcaseBusiness, Clock3, MapPin, Search, ShieldCheck, UsersRound } from 'lucide-react';
import Avatar from './Avatar.jsx';

export function SearchSection({ t, query, setQuery, location, setLocation, filters = {}, setFilters = () => {}, onSearch, busy = false, pin = '', setPin = () => {}, radius = '30', setRadius = () => {}, geoNote = null }) {
  const updateFilter = (key) => (event) => setFilters((current) => ({ ...current, [key]: event.target.value }));
  return <section className="search-section wrap" aria-label="Search nearby workers and jobs"><form className="search-box" onSubmit={onSearch}>
    <label className="search-field"><Search size={19}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.searchPlaceholder} aria-label={t.searchPlaceholder}/></label><span className="search-divider"/><label className="location-field"><MapPin size={18}/><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder={t.locationPlaceholder} aria-label={t.locationPlaceholder}/></label><span className="search-divider"/><label className="pin-field"><MapPin size={18}/><input value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, '').slice(0, 6))} inputMode="numeric" maxLength={6} placeholder={t.pinPlaceholder} aria-label={t.pinPlaceholder}/></label><label className="radius-field"><select value={radius} onChange={(event) => setRadius(event.target.value)} aria-label="Distance">{['10', '20', '30', '50', '100'].map((km) => <option key={km} value={km}>{t.withinKm} {km} km</option>)}<option value="any">{t.anyDistance}</option></select></label><button className="button button-green" type="submit" disabled={busy}>{busy ? '…' : t.search}<ArrowRight size={15}/></button>
  </form><details className="search-filters"><summary>{t.moreFilters}</summary><div className="search-filter-grid">
    <label>{t.profession}<input value={filters.profession || ''} onChange={updateFilter('profession')} placeholder={t.professionExample}/></label>
    <label>{t.experienceYears}<div className="filter-range"><input type="number" min="0" placeholder={t.min} value={filters.minExperience || ''} onChange={updateFilter('minExperience')}/><input type="number" min="0" placeholder={t.max} value={filters.maxExperience || ''} onChange={updateFilter('maxExperience')}/></div></label>
    <label>{t.workerRate}<div className="filter-range"><input type="number" min="0" placeholder={t.min} value={filters.minRate || ''} onChange={updateFilter('minRate')}/><input type="number" min="0" placeholder={t.max} value={filters.maxRate || ''} onChange={updateFilter('maxRate')}/></div></label>
    <label>{t.availability}<select value={filters.available || ''} onChange={updateFilter('available')}><option value="">{t.any}</option><option value="true">{t.available}</option><option value="false">{t.notAvailable}</option></select></label>
    <label>{t.workType}<select value={filters.workType || ''} onChange={updateFilter('workType')}><option value="">{t.any}</option><option value="hourly">{t.hourly}</option><option value="contract">{t.contract}</option><option value="part-time">{t.partTime}</option><option value="full-time">{t.fullTime}</option></select></label>
    <label>{t.jobType}<select value={filters.jobType || ''} onChange={updateFilter('jobType')}><option value="">{t.any}</option><option value="hourly">{t.hourly}</option><option value="contract">{t.contract}</option><option value="part-time">{t.partTime}</option><option value="full-time">{t.fullTime}</option></select></label>
    <label>{t.jobPay}<div className="filter-range"><input type="number" min="0" placeholder={t.min} value={filters.minPay || ''} onChange={updateFilter('minPay')}/><input type="number" min="0" placeholder={t.max} value={filters.maxPay || ''} onChange={updateFilter('maxPay')}/></div></label>
  </div></details>{geoNote ? <p className="search-hint">Showing workers and jobs within {geoNote.radiusKm} km of PIN {geoNote.pinCode}, nearest first.{geoNote.skippedUnknownPin ? ` (${geoNote.skippedUnknownPin} without a known PIN code not shown.)` : ''}</p> : <p className="search-hint">{t.locationHelp}</p>}</section>;
}

export function StatsSection({ t, stats }) {
  const show = (value) => (value === null || value === undefined ? '–' : value);
  return <section className="stats-strip"><div className="wrap stats-inner"><div className="stats-intro"><span>{t.nearby}</span><h2>{t.trusted}</h2><p>{t.trustedSub}</p></div><div className="stat"><strong>{show(stats?.workers)}</strong><small>{t.workers}</small></div><div className="stat"><strong>{show(stats?.jobs)}</strong><small>{t.jobs}</small></div><div className="stat"><strong>{show(stats?.areas)}</strong><small>{t.activeAreas}</small></div></div></section>;
}

export function WorkerSection({ t, people, onContact, onViewProfile }) {
  return <section className="section wrap" id="discover"><div className="section-heading"><div><div className="eyebrow eyebrow-muted"><span className="eyebrow-dot"/>{t.nearby}</div><h2>{t.workersTitle}</h2><p>{t.workersSub}</p></div><a className="link-arrow" href="#workers">{t.viewWorkers}<ArrowUpRight size={16}/></a></div>
    <div className="card-grid worker-grid" id="workers">{people.length ? people.map((person) => <article className="worker-card" key={person._id || person.id || person.name}><div className="worker-card-top"><Avatar initials={person.initials} color={person.color} large/><span className="available-pill"><span/>{person.availability === false ? 'Unavailable' : t.available}</span></div><div className="worker-name-row"><h3>{person.name}</h3><span className="verified-icon" title={`${person.rating || 0} stars · ${person.reviewCount || 0} reviews`}><ShieldCheck size={17}/></span></div><div className="worker-role">{person.role} <span>·</span> {person.exp}</div><p className="worker-work">{person.work}</p><div className="tag-row">{person.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="card-footer"><span className="place"><MapPin size={14}/>{person.area}{person.distance ? <> <span>·</span> <span className="distance-chip">{person.distance} {t.away}</span></> : null}</span><span className="rate"><small>{person.rating ? `★ ${person.rating} · ` : ''}</small>{person.rate}<small>{person.unit}</small></span></div><button className="profile-card-action" onClick={() => onViewProfile(person)}>View profile and reviews</button><button className="card-action" onClick={() => onContact(person)}>{t.contact}<ArrowRight size={15}/></button></article>) : <div className="empty-state">No workers match that search yet. Try a different skill or location.</div>}</div>
  </section>;
}

export function JobsSection({ t, jobs, onJob }) {
  return <section className="jobs-band" id="jobs"><div className="wrap section jobs-section"><div className="section-heading"><div><div className="eyebrow eyebrow-muted"><span className="eyebrow-dot"/>{t.nearby}</div><h2>{t.jobsTitle}</h2><p>{t.jobsSub}</p></div><a className="link-arrow" href="#jobs">{t.viewJobs}<ArrowUpRight size={16}/></a></div><div className="job-list">{jobs.length ? jobs.map((job) => <article className="job-card" key={job._id || job.id || job.title}><Avatar initials={job.initials} color={job.tone}/><div className="job-main"><h3>{job.title}</h3><div className="job-poster">{job.poster} <span>·</span> {job.category}</div><div className="job-meta"><span><MapPin size={13}/>{job.place}{job.distance ? <> · <span className="distance-chip">{job.distance} {t.away}</span></> : null}</span><span><Clock3 size={13}/>{job.duration}</span></div></div><div className="job-pay"><strong>{job.pay}</strong><span>{job.kind}</span></div><button className="job-arrow" aria-label={t.apply} onClick={() => onJob(job)}><ArrowUpRight size={19}/></button></article>) : <div className="empty-state">No jobs match that search yet. Try another skill or location.</div>}</div></div></section>;
}

export function HowItWorksSection({ t }) {
  return <section className="section wrap how-section" id="how"><div className="section-heading centered"><div><div className="eyebrow eyebrow-muted"><span className="eyebrow-dot"/>{t.navHow}</div><h2>{t.howTitle}</h2><p>{t.howSub}</p></div></div><div className="steps-grid"><article className="step-card"><span className="step-number">01</span><div className="step-icon"><UsersRound size={21}/></div><h3>{t.step1}</h3><p>{t.step1Text}</p><ArrowDownRight className="step-arrow" size={18}/></article><article className="step-card"><span className="step-number">02</span><div className="step-icon"><Search size={21}/></div><h3>{t.step2}</h3><p>{t.step2Text}</p><ArrowDownRight className="step-arrow" size={18}/></article><article className="step-card"><span className="step-number">03</span><div className="step-icon"><BriefcaseBusiness size={21}/></div><h3>{t.step3}</h3><p>{t.step3Text}</p><ArrowDownRight className="step-arrow" size={18}/></article></div></section>;
}

export function CommunityCallout({ t }) {
  return <section className="community-cta wrap"><div className="cta-decoration">✳</div><div><span className="cta-kicker">RURAL COMPANY</span><h2>{t.trustTitle}</h2><p>{t.trustText}</p></div><a href="#choose" className="button button-cream">{t.trustCta}<ArrowRight size={16}/></a></section>;
}
